# Generated by Django 3.1.1 on 2022-01-12 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=45)),
                ('price', models.IntegerField(verbose_name='product_price')),
                ('description', models.TextField(verbose_name='product_info')),
                ('stock', models.IntegerField(verbose_name='product_stock')),
                ('date', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'product',
                'db_table': 'vitamin_product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='modification_date ')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'vitamin_user',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitaminapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Order_time')),
                ('order_pic', models.ImageField(blank=True, null=True, upload_to='order_images')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitaminapp.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitaminapp.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'db_table': 'vitamin_order',
            },
        ),
    ]
