# Generated by Django 3.1.1 on 2022-01-13 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitaminapp', '0002_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cart_id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vitaminapp.product'),
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='OrderProduct',
        ),
    ]
