# Generated by Django 3.1.1 on 2022-01-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitaminapp', '0003_auto_20220113_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(default='', to='vitaminapp.OrderProduct'),
        ),
    ]
